# Coding Challenge - 2
This week we will create a Python 3 function for the Gram-Schmidt Orthonormalization Process. Why? Because you need to be good at making **for loops** to make such a function!


**Further reading:**
1.   [khanacademy.org](https://www.khanacademy.org/math/linear-algebra/alternate-bases/orthonormal-basis/v/linear-algebra-the-gram-schmidt-process)
2.   [wikipedia.org](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)



## Gram-Schmidt Orthonormalization Process

It has three steps.
1. Begin with a basis for the inner product space. It need not be orthogonal nor
consist of unit vectors.
2. Convert the basis to an orthogonal basis.
3. Normalize each vector in the orthogonal basis to form an orthonormal basis

![alt text](https://image.ibb.co/eU84mL/gs-process.png)

## The challenge
Create a python 3 function to pass a multidimensional list of vectors and appy the gram-schmidt process for orthoganolization.

Hint, use numpy to save time! 
https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html

**Example output:**

```
Given B = 

[[1 1 0]
 [1 2 0]
 [0 1 2]]

B' is an orthogonal basis for R3

[[ 1.   1.   0. ]
 [-0.5  0.5  0. ]
 [ 0.   0.   2. ]]

and B'' is an orthonormal basis for R3

[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
```

**Another example**

```
Given B = 

[[0 1 1]
 [1 1 0]
 [1 0 1]]

B' is an orthogonal basis for R3

[[ 0.          1.          1.        ]
 [ 1.          0.5        -0.5       ]
 [ 0.66666667 -0.66666667  0.66666667]]

and B'' is an orthonormal basis for R3

[[ 0.          0.70710678  0.70710678]
 [ 0.81649658  0.40824829 -0.40824829]
 [ 0.57735027 -0.57735027  0.57735027]]
```

