# Coding Challenge - 2
This week we will create a Python 3 function for the Gram-Schmidt Orthonormalization Process. Why? Because you need to be good at making **for loops** to make such a function!


**Further reading:**
1.   [khanacademy.org](https://www.khanacademy.org/math/linear-algebra/alternate-bases/orthonormal-basis/v/linear-algebra-the-gram-schmidt-process)
2.   [wikipedia.org](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)



## Gram-Schmidt Orthonormalization Process

It has three steps.
1. Begin with a basis for the inner product space. It need not be orthogonal nor
consist of unit vectors.
2. Convert the basis to an orthogonal basis.
3. Normalize each vector in the orthogonal basis to form an orthonormal basis

![alt text](https://image.ibb.co/eU84mL/gs-process.png)

## The challenge
Create a python 3 function to pass a multidimensional list of vectors and appy the gram-schmidt process for orthoganolization.

Hint, use numpy to save time! 
https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html

**Example output:**

```
Given B = 

[[1 1 0]
 [1 2 0]
 [0 1 2]]

B' is an orthogonal basis for R3

[[ 1.   1.   0. ]
 [-0.5  0.5  0. ]
 [ 0.   0.   2. ]]

and B'' is an orthonormal basis for R3

[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
```

**Another example**

```
Given B = 

[[0 1 1]
 [1 1 0]
 [1 0 1]]

B' is an orthogonal basis for R3

[[ 0.          1.          1.        ]
 [ 1.          0.5        -0.5       ]
 [ 0.66666667 -0.66666667  0.66666667]]

and B'' is an orthonormal basis for R3

[[ 0.          0.70710678  0.70710678]
 [ 0.81649658  0.40824829 -0.40824829]
 [ 0.57735027 -0.57735027  0.57735027]]
```



In [3]:
"""
This python code is for the Gram-Schmidt Orthonormalization Process

I used the following API:
https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html

Name: gramSchmidt.py 
Version: v.1.0.1
Written in Python 3
By Edgard Parra
"""

# Numpy will be used to do most mathematical functions
import numpy as np

''' Step 1 - Let B be a basis for an inner product space '''

B = np.array([[1, 1, 0], [1, 2, 0], [0, 1, 2]])

''' Step 2 - Find and orthogonal basis for V, call it W or something '''


def gramSchmidt(B):
	''' 
	This function takes a set of vector as input 
	and returns an orthonormal basis for it
	'''
	
	# this array will hold the orthogonal basis for V
	b = []
	
	# w1 = v1
	b.append(B[0])
    
    # The Gram-Schmidt Orthonormalization Process in python for loop
	for v in B[1:]:
		# math = vi - <vi,wi>/<wi,wi> * wi
		u = v - np.sum( (np.inner(v,w)/np.inner(w,w) * w) for w in b)
		
		# append our resultant orthogonal vector
		b.append(u)
	
	# b is an orthogonal basis in V
	b = np.array(b)
	
	''' Step 3 - Lets normalize the basis! '''
	
	# this array will hold the orthonormal basis for V
	u = []
	
	for w in b:
		# find the norm of vector w in b
		norm = np.sqrt( np.inner(w,w) )
		
		# normalize each vector
		x = w / norm
		
		# append our results
		u.append(x)
	
	# u is an orthonormal basis in V
	u = np.array(u)

	# print our results for test purposes and should be commented out
	
	# dimension of vector space
	dim = str(len(B))
	
	print('Given B = \n')
	print(B)
	
	print('\nB\' is an orthogonal basis for R' + dim + '\n')
	print(b)
	
	print('\nand B\'\' is an orthonormal basis for R' + dim + '\n')
	print(u)
	
	# return orthonormal basis
	return(u)
    
# execute the funtion!
gramSchmidt(B)

Given B = 

[[1 1 0]
 [1 2 0]
 [0 1 2]]

B' is an orthogonal basis for R3

[[ 1.   1.   0. ]
 [-0.5  0.5  0. ]
 [ 0.   0.   2. ]]

and B'' is an orthonormal basis for R3

[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [4]:
print('Problem 25')
B = np.array([[0, 1, 1], [1, 1, 0], [1, 0, 1]])
gramSchmidt(B)

Problem 25
Given B = 

[[0 1 1]
 [1 1 0]
 [1 0 1]]

B' is an orthogonal basis for R3

[[ 0.          1.          1.        ]
 [ 1.          0.5        -0.5       ]
 [ 0.66666667 -0.66666667  0.66666667]]

and B'' is an orthonormal basis for R3

[[ 0.          0.70710678  0.70710678]
 [ 0.81649658  0.40824829 -0.40824829]
 [ 0.57735027 -0.57735027  0.57735027]]


array([[ 0.        ,  0.70710678,  0.70710678],
       [ 0.81649658,  0.40824829, -0.40824829],
       [ 0.57735027, -0.57735027,  0.57735027]])