# Python Lecture - 5

## Index Review

In [2]:
'''
  Index of a list
'''

anIndex = [9,78,2,3,4,5]

print('index 0 =',anIndex[0])
print('index 1 =',anIndex[1])
print('index 2 =',anIndex[2])
print('index 3 =',anIndex[3])
print('index 4 =',anIndex[4])
print('index 5 =',anIndex[5])

index 0 = 9
index 1 = 78
index 2 = 2
index 3 = 3
index 4 = 4
index 5 = 5


In [1]:
'''
  Index of a multidimensional list
'''

multiList = [[1,2,3],
             [4,5,6],
             [7,8,9]]

print('index 0',multiList[0])
print('index 1',multiList[1])
print('index 2',multiList[2])

print('index 0-0 =',multiList[0][0])
print('index 1-0 =',multiList[1][0])
print('index 2-0 =',multiList[2][0])

index 0 [1, 2, 3]
index 1 [4, 5, 6]
index 2 [7, 8, 9]
index 0-0 = 1
index 1-0 = 4
index 2-0 = 7


## For Loops

In [0]:
'''
  For loops are used to traverse through data
'''

aListofData = [3123,315675,32432,8744]

for row in aListofData:
  print(row)

In [3]:
'''
  For loops can be used to do math to your data
'''

anIndex = [9,78,2,3,4,5]

for row in anIndex:
  x = row * 3
  print(x)

27
234
6
9
12
15


In [0]:
'''
  Notice the behavior of for loops with multidimensional lists
'''

multiList = [[1,2,3],
             [4,5,6],
             [7,8,9]]

for row in multiList:
  print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [0]:
'''
  Notice the behavior of for loops with multidimensional lists
'''

multiList = [[1,2,3],
             [4,5,6],
             [7,8,9]]

for row in multiList:
  for item in row:
    print(item)

1
2
3
4
5
6
7
8
9


In [0]:
'''
  you can change the name to whatever you like, but keep it something relatable
'''

for adam in multiList:
  print(adam)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [0]:
# https://docs.python.org/3/library/functions.html#func-range 
# range(start, stop[, step])

for row in range(0,11):
  print(row)

0
1
2
3
4
5
6
7
8
9
10


In [12]:
multiList = [[1,2,3],
             [4,5,6],
             [7,8,9]]

print(multiList)

myResults = []

for row in multiList:
  row[0] = row[0] * 5
  row[1] = row[1] * 3
  row[2] = row[2] / 2
  myResults.append(row)

"""for row in multiList:
  row[0] = row[0] * 5
  row[1] = row[1] * 3
  row[2] = row[2] / 2
  myResults.append(row)"""
  
print(myResults)

def multiplyList(x):
  for row in x:
    row[0] = row[0] * 5
    row[1] = row[0] * 3
    row[2] = row[0] /2
    
    print(row)

print(multiplyList(multiList))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[5, 6, 1.5], [20, 15, 3.0], [35, 24, 4.5]]
[25, 75, 12.5]
[100, 300, 50.0]
[175, 525, 87.5]
None


## The most simple way of looking at For Loops

Lets imagine we have data from an excel file

![excel data](https://image.ibb.co/f3UdD0/excel-data.png)

Importing the data to a python list would yield: 


```
anExcelFile = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```

So lets write some code that simplifies For loops as much as possible.

In [0]:
'''
  Lets write python in plain english
'''

anExcelFile = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

myResults = []

for row in anExcelFile:
  columnA = row[0] * 2
  columnB = row[1]
  columnC = row[2]
  
  row = [columnA,columnB,columnC]
  myResults.append(row)

print(myResults)

[[2, 2, 3], [8, 5, 6], [14, 8, 9]]


In [0]:
'''
  Example of how easy it is to implement math
'''

import numpy as np
from numpy import linalg as LA

w, v = LA.eig(np.diag((1, 2, 3)))

print(w)
print(v)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
